name: tests & build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
          activate-environment: bids_atlas
          use-mamba: false
          channels: conda-forge, defaults
          python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pip install -r requirements-dev.txt
    - name: Install bids_atlas
      shell: bash -l {0}
      run: |
        pip install ./
    - name: Test code
      shell: bash -l {0}
      run: |
        coverage run -m pytest
        coverage report -m
        codecov
        flake8
    - name: Build the docs
      shell: bash -l {0}
      run: |
        cd docs && make clean html
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        commit_message: ${{ github.event.head_commit.message }}
