name: tests

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Install bids_atlas
      run: |
        pip install -e ./
    - name: Debug structure
      run: |
        find . -name "test_*.py" -type f
        ls -la bids_atlas/tests/
    - name: Test code
      shell: bash -l {0}
      run: |
        python -m pytest bids_atlas/tests/ -v
    - name: Lint code
      shell: bash -l {0}
      run: |
        flake8 bids_atlas/ --config=.flake8
